# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNative
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  ]
  
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end
